---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test2-dev
  namespace: argocd
spec:
  destination:
    namespace: test2-dev-deploy
    server: "cluster url"
  source:
    path: apps/test2/overlays/test/
    repoURL: "git url for deploy repo"
    targetRevision: master
    directory:
      recurse: false
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
  project: test2
---
